M48
; DRILL file {KiCad (6.0.10-0)} date Friday, March 03, 2023 at 02:43:51 PM
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-03-03T14:43:51-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.10-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1280
%
G90
G05
T1
X3.153Y-3.1768
X3.153Y-3.6768
X3.153Y-3.9484
X3.153Y-4.4484
T0
M30
