M48
; DRILL file {KiCad (6.0.10-0)} date Wednesday, March 08, 2023 at 10:25:38 AM
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-03-08T10:25:38-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.10-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1280
%
G90
G05
T1
X3.153Y-3.1768
X3.153Y-3.6768
X3.153Y-3.9484
X3.153Y-4.4484
T0
M30
